### ISSUE TITLE
docker-pgbackrest for bitnami/postgresql-repmgr

### ISSUE THREAD

**Issue by TamarNR** [woblerr/docker-pgbackrest#10]
Hi,

I have a postgreSql running inside a container  using this:
https://github.com/bitnami/bitnami-docker-postgresql

I would like to backup my postgres (the Primary only), using docker-pgbackrest.

I that possible?
If so - how should i run the docker-pgbackrest container to know about the postgres container?

Thanks,
Tamar

**Comment by woblerr** [comment]
Hi,

As I see, the [bitnami-docker-postgresql](https://github.com/bitnami/bitnami-docker-postgresql) image already contains parameters for pgbackrest: [L323-L328](https://github.com/bitnami/bitnami-docker-postgresql/blob/a254279d652ee7e9e8cd675d71db3936e226fcc8/14/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh#L323-L328). 
You need to configure WAL archiving for PostgreSQL instance and add to container the correct config for pgBackRest. After that, you can perform backups from the container.
How to do this correctly, you need to ask the project maintainers.

If the main task is to perform backups through an external image (like dedicated repository host), then you can use, for example, [pgBackRest TLS server](https://pgbackrest.org/user-guide-rhel.html#repo-host/config).
Anyway, as a first step, you need to correctly configure PostgreSQL instance and pgBackRest inside your container.
As a second step, you can run `docker-pgbackrest` image as dedicated repository host, using pgBackRest TLS server to communicate with the PostgreSQL container. A simple example is given in docs: [use-tls](https://github.com/woblerr/docker-pgbackrest#use-tls).
