### ISSUE TITLE
Dedicated backup repository

### ISSUE THREAD

**Issue by YaserAmini88** [woblerr/docker-pgbackrest#23]
I have a postgresql cluster(1 master + 2 slaves) and I want to use pgbackrest for backup and restore. Unfortunately, the details on this repository is pretty vague and I couldn't  make it work. I have a dedicated server which should be used as repository and here's my questions:

1. In pgbackrest doc page on dedicated repository section, it is explained that we should have a client/server configuration for pgbackrest to work. But in your repo I cannot see that. It's just a docker image that should be run on dedicated server and no configuration has been explained in side of actual postgresql server.

2. You have two volumes in your docker command: -v /etc/pgbackrest:/etc/pgbackrest and -v /var/lib/pgbackrest:/var/lib/pgbackrest.
I have not these directory on the dedicated server. Should I create them manually ? What kind of files must be inside these directories and with what configuratiosn? In your Dockerfile you just touch the pgbackrest.conf without any sample configurations.

3. I want to use TLS for communication. This is the official doc: https://www.postgresql.org/docs/current/ssl-tcp.html
But I cannot understand how to make it work. Section 19.9.5 explains the certificate issuing. I know that I have execute them on master server but should I copy crt,ca and key files to the pgbackrest dedicated server? What's the actual configuration for connecting to master server from dedicated server? By the way, the commands described in the link do not generate a ca file.

**Comment by woblerr** [comment]
Hi

1. This image can be useful for refusing to install pgBackRest as a system package (using yum or apt, for example) on your dedicated server or inside CI/CD pipelines. You can just run pgBackRest in docker. At the same time, the postgresql server side must be configured according to the pgBackRest documentation. There is no magic here.

2. According pgBackRest documentation:
* /etc/pgbackrest - basic path, where pgBackRest stores configs. Yes, when you install pgBackRest, for example, from rpm package, there isn't this folder. Only /etc/pgbackrest.conf file. But see description in [3.1 section of pgBackRest docs](https://pgbackrest.org/user-guide-rhel.html#upgrading/v1-v2).
* /var/lib/pgbackrest - basic repository path, where pgBackRest stores backups (see [6.3](https://pgbackrest.org/user-guide.html#quickstart/create-repository)) <br>
So, if you store your pgBackRest configurations  files on dedicated host or you want to store backups on server disk, you should mount nesessary files and directories  into container. 

3. For setup TLS server for pgBackRest see [17.2](https://pgbackrest.org/user-guide-rhel.html#repo-host/config) and [17.3](https://pgbackrest.org/user-guide-rhel.html#repo-host/setup-tls) sections in pgBackRest documentation.<br> 
[Examples](https://github.com/woblerr/docker-pgbackrest/tree/master/e2e_tests#use-tls) of how to generate selfsigned certificates and use them (don't do this on your production!) and some examples of pgBackRest configuration files are in e2e_tests folder: [postgresql](https://github.com/woblerr/docker-pgbackrest/blob/master/e2e_tests/conf/pg/pg_pgbackrest-tls.conf), [dedicated](https://github.com/woblerr/docker-pgbackrest/blob/master/e2e_tests/conf/backup/backup_pgbackrest-tls.conf)
