### ISSUE TITLE
Unable to Restore Backup with pgBackRest on a Docker Container with PostgreSQL Service

### ISSUE THREAD

**Issue by zN3utr4l** [woblerr/docker-pgbackrest#32]
I opened this issue on pgbackrest (https://github.com/pgbackrest/pgbackrest/issues/2134), it's not very clear to me.

I found this github repository and I think it's the one for me, but I don't see examples of restore.

I have already configured pgbackrest on a postgres instance, I make backups there, can I take them and take them to another postgres instance not connected in any way to the first one?

**Comment by zN3utr4l** [comment]
I wanted to ask if even with pgbackrest in tls version there is a need for file access.
As I said above, **"I have already configured pgbackrest on a postgres instance, I make backups there"**, if I configure docker-pgbackrest locally, I can't access the repository on the remote server where I made the backups? obviously putting everything online reachable

**Comment by woblerr** [comment]
Did I understand correctly that there is a configured pg instance and a dedicated pgbackrest host  and communication is carried out via [TLS](https://pgbackrest.org/user-guide-rhel.html#repo-host/config)?

If you have correctly configured pgbackrest via TLS, then nothing prevents you from connecting from a local machine to a dedicated pgbackrest host using a tls connection.

You need to configure the certificates  and pgbackrest config correctly, of course.

**Comment by zN3utr4l** [comment]
No, I currently have a postgres server with pgbackrest installed in it, not through this docker container.

I was wondering if by uninstalling pgbackrest in the postgres container and installing the following container by configuring it with TLS I can always make backups from this container and then later, randomly, how can I restore this db instance on another empty instance locally?

Or even can I keep the pgbackrest instance installed in the already present docker postgres container and configure it to use it with TLS?

**Comment by woblerr** [comment]
> I was wondering if by uninstalling pgbackrest in the postgres container and installing the following container by configuring it with TLS I can always make backups from this container and then later, randomly, how can I restore this db instance on another empty instance locally?

For WAL archiving to work correctly, you need a pgBackRest inside your PG container. This image can be useful for refusing to install pgBackRest as a system package (using yum or apt, for example) on your dedicated server or inside CI/CD pipelines. You can just run pgBackRest in docker. At the same time, the postgresql server side must be configured according to the pgBackRest documentation.

**Comment by zN3utr4l** [comment]
OK, everything is clearer to me after this discussion (https://github.com/pgbackrest/pgbackrest/issues/2134#issuecomment-1658405159), I wanted to ask a question though, now I have timescale on a docker container, (timescale/timescaledb :2.11.1-pg14), if I try to stop it to perform a restore, the container is also stopped, as its main service is stopped, how can I perform a restore without the container shutting down?

**Comment by woblerr** [comment]
Probably, it is correct to ask this question to the authors of this container.

However, I will assume that you can go two ways:
1. Perform a recovery using the mounted volume for PGDATA and then launch a new container using this volume.
2. Or create your own image based on this one, which will perform recovery before starting the main process.

However, these are just assumptions and it's up to you to decide which way to go.
